name: boilerplate_flutter
description: "A Crosby's Custom Starter Project Boilerplate Flutter ."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  bloc: ^8.1.2
  dartz: ^0.10.1
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_gen_runner: ^5.3.2
  gap: ^3.0.1
  get: ^4.6.6
  get_it: ^7.6.4
  intl: ^0.19.0
  json_annotation: ^4.8.1
  mockito: ^5.4.4
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.2

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Circular
      fonts:
        - asset: assets/font/circular.otf
  assets:
    - assets/img/
    - assets/font/
    - assets/svg/
